version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION:-1.24-alpine}
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - frontend
      - app
    restart: unless-stopped

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
    volumes:
      - ./backend:/app
    depends_on:
      - timescaledb
      - mqtt
    environment:
      - TZ=UTC
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - app
    environment:
      - TZ=UTC
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=weather_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    expose:
      - "1883"
      - "9001"
    volumes:
      - ./backend/mqtt/config:/mosquitto/config
      - ./backend/mqtt/data:/mosquitto/data
      - ./backend/mqtt/log:/mosquitto/log
    restart: unless-stopped

volumes:
  timescaledb_data: 